background = '#2e3440'
foreground = '#d8dee9'

color00 = '#2e3440'
color01 = '#bf616a'
color02 = '#a3be8c'
color03 = '#ebcb8b'
color04 = '#81a1c1'
color05 = '#b48ead'
color06 = '#88c0d0'
color07 = '#e5e9f0'

color08 = '#4c566a'
color15 = '#eceff4'

color16 = '#d08770'
color17 = '#5e81ac'
color18 = '#3b4252'
color19 = '#4c566a'
color20 = '#d8dee9'
color21 = '#eceff4'
